### ISSUE TITLE
policy iteration doesn't work for deterministic frozen_lake env

### ISSUE THREAD

**Issue by huiwenzhang** [ucla-rlcourse/RLexample#5]
I am trying to use the code as an example. Well, it is a little bit strange, when I changed the frozen lake env to the deterministic version, e.g. `env = gym.make("FrozenLake=v0, is_slippery=False)`,  I found the policy iteration algorithm can't work correctly. I checked the code, it seems nothing wrong. One of the reason might be the insufficient exploration of the agent, however, the env is simple enough and the default iteration numbers are set to 200000. But the problem still can't be solved.

**Comment by pengzhenghao** [comment]
Your guess is correct. We don't have an episilon-greedy exploration for PI so there is no exploration at all. Because you are using a deterministic environment, and the policy is also deterministic (argmax policy always taking the same action). The agent will immediately fall into local minima and never get out.
